import type { Metadata } from 'next'
import './globals.css'
import { ProviderQuery, ProviderStorage } from '@/components'
import type { _metaDate } from '@/types/metaDate'

export const metadata: Metadata = {
  title: 'WellCars',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <ProviderQuery>
        <ProviderStorage>
          <body className={` antialiased`}>{children}</body>
        </ProviderStorage>
      </ProviderQuery>
    </html>
  )
}
