import type { Metadata } from 'next'
import './globals.css'
import { ProviderQuery, ProviderStorage } from '@/components'
import type { _metaDate } from '@/types/metaDate'
import {Jersey_20} from 'next/font/google'

export const metadata: Metadata = {
  title: 'WellCars',
  description: 'Generated by create next app',
}

const jersey_20 = Jersey_20({weight:'400',subsets: ['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <ProviderQuery>
        <ProviderStorage>
          <body className={` antialiased ${jersey_20.className}`}>{children}</body>
        </ProviderStorage>
      </ProviderQuery>
    </html>
  )
}
